# Generated by Django 5.2.17 on 2026-09-15 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id_estado_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'estados_cuenta',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('name_surname', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=150, unique=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('date_nacimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado_cuenta', models.ForeignKey(blank=True, db_column='id_estado_cuenta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='web.estadocuenta')),
                ('rol', models.ForeignKey(db_column='role', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='web.rol')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id_asistente', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.CASCADE, related_name='asistentes_a_cargo', to='web.usuario')),
                ('usuario', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='asistente', to='web.usuario')),
            ],
            options={
                'db_table': 'asistente',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('fecha_alta_matricula', models.DateField(blank=True, null=True)),
                ('ente_otorgante', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='web.usuario')),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
    ]
