# Generated by Django 5.2.17 on 2026-09-16 20:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoHistorial',
            fields=[
                ('id_motivo_historial', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=30)),
                ('motivo', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'motivo_historial',
            },
        ),
        migrations.CreateModel(
            name='Consorcio',
            fields=[
                ('id_consorcio', models.AutoField(primary_key=True, serialize=False)),
                ('name_consorcio', models.CharField(max_length=150)),
                ('img_consorcio', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('representante', models.ForeignKey(db_column='representante', on_delete=django.db.models.deletion.PROTECT, related_name='consorcios_administrados', to='web.usuario')),
            ],
            options={
                'db_table': 'consorcio',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='historial_generado', to='web.usuario')),
                ('usuario_involucrado', models.ForeignKey(blank=True, db_column='id_user_involucrado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_involucrado', to='web.usuario')),
                ('motivo', models.ForeignKey(db_column='id_motivo_historial', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='web.motivohistorial')),
            ],
            options={
                'db_table': 'historial',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDoc',
            fields=[
                ('id_historial_doc', models.AutoField(primary_key=True, serialize=False)),
                ('doc', models.CharField(max_length=255)),
                ('historial', models.ForeignKey(db_column='id_historial', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='web.historial')),
            ],
            options={
                'db_table': 'historial_doc',
            },
        ),
        migrations.CreateModel(
            name='AsistenteConsorcio',
            fields=[
                ('id_asistente_consorcio', models.AutoField(primary_key=True, serialize=False)),
                ('habilitado', models.BooleanField(default=True)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consorcios_asignados', to='web.asistente')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistentes_asignados', to='web.consorcio')),
            ],
            options={
                'db_table': 'asistente_consorcio',
                'constraints': [models.UniqueConstraint(fields=('asistente', 'consorcio'), name='uq_asistente_consorcio')],
            },
        ),
    ]
