# Generated by Django 5.2.17 on 2026-09-17 20:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_motivohistorial_consorcio_historial_historialdoc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='TipoChat',
            fields=[
                ('id_tipo_chat', models.AutoField(primary_key=True, serialize=False)),
                ('name_chat', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_chat',
            },
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('enviado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(db_column='id_chat', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='web.chat')),
                ('usuario', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='web.usuario')),
            ],
            options={
                'db_table': 'mensaje_chat',
                'ordering': ['enviado_en'],
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='tipo_chat',
            field=models.ForeignKey(db_column='id_tipo_chat', on_delete=django.db.models.deletion.PROTECT, related_name='chats', to='web.tipochat'),
        ),
        migrations.CreateModel(
            name='MiembroChat',
            fields=[
                ('id_miembro', models.AutoField(primary_key=True, serialize=False)),
                ('chat', models.ForeignKey(db_column='id_chat', on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='web.chat')),
                ('usuario', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='chats_de_los_que_participa', to='web.usuario')),
            ],
            options={
                'db_table': 'miembros_chat',
                'constraints': [models.UniqueConstraint(fields=('chat', 'usuario'), name='uq_miembro_por_chat')],
            },
        ),
    ]
